version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-sample
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001